language: ruby
rvm:
  - 2.1.0
before_script:
  - psql -c 'create database breakpoint_app_test;' -U postgres
  - export RUBY_GC_MALLOC_LIMIT=50000000
  - bundle exec rake db:migrate
bundler_args: --without development
cache: bundler
script: 'bundle exec rspec'
services:
  - redis-server
