language: ruby
rvm:
  - 2.1.1
before_script:
  - cp config/database.yml.travis config/database.yml
  - psql -c 'create database breakpoint_app_test;' -U postgres
  - export RUBY_GC_MALLOC_LIMIT=50000000
  - RAILS_ENV=test bundle exec rake db:schema:load
bundler_args: --without development
cache: bundler
script: 'bundle exec rspec'
services:
  - redis-server
